// Requires Playwright (or NODE_PATH pointing to it), installed Chrome, and the local server.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
(async () => {
 const browser = await chromium.launch({channel:'chrome', headless:true});
 try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const openOptions = async () => { if (!await page.locator('#modeButtons').isVisible()) await page.click('#moreOptions > summary'); };
  const chooseView = async view => { await openOptions(); await page.click(`[data-mode="${view}"]`); };
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.PREVIEW_URL || 'http://127.0.0.1:4173');
  await page.waitForSelector('#chart polyline');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('#chart polyline').count(),4);
  assert.equal(await page.locator('#modeButtons').isVisible(),false,'advanced controls start tucked away');
  assert.equal(await page.locator('.toolbar > .control-group').count(),3);
  assert.equal(await page.locator('.result-growth').count(),4,'money and percentage appear together');
  assert.match(await page.locator('.result-value').first().innerText(),/^Rp/);
  const chartBox=await page.locator('.chart-panel').boundingBox();
  const resultsBox=await page.locator('.comparison-panel').boundingBox();
  assert.equal(chartBox.y,resultsBox.y,'chart and results share a row on desktop');
  assert.ok(resultsBox.x>chartBox.x+chartBox.width,'results sit alongside chart');
  const originalColor=await page.locator('#chart [data-series="BBCA"] polyline').getAttribute('stroke');
  for(const [preset,count] of [['banks',4],['gold',3],['commodities',4],['nickel',4],['market',3],['default',4]]) {
   await page.click(`[data-preset="${preset}"]`);
   assert.equal(await page.locator('#chart polyline').count(),count,preset);
   assert.equal(await page.locator('#comparisonResults .comparison-row').count(),count);
   assert.equal(await page.locator(`[data-preset="${preset}"]`).getAttribute('aria-pressed'),'true');
  }
  await page.click('[data-collection="world"]');
  assert.equal(await page.locator('.world-market').count(),9);
  for(const [preset,count] of [['global',4],['neighbours',3],['asia',4],['us',4]]) {
   await page.click(`[data-preset="${preset}"]`);
   assert.equal(await page.locator('#chart polyline').count(),count,preset);
  }
  await page.click('[data-preset="global"]');
  await page.selectOption('#currencySelect','USDIDR');
  assert.match(await page.locator('#worldContext').innerText(),/US Dollar/);
  await page.click('[data-market="KLCI"]');
  assert.equal(await page.locator('#chart [data-series="KLCI"]').count(),1);
  await page.click('[data-market="KLCI"]');
  assert.equal(await page.locator('#chart [data-series="KLCI"]').count(),0);
  await page.selectOption('#currencySelect','AUDIDR');
  const periodBefore=await page.evaluate(()=>[state.startDate,state.endDate]);
  await page.click('[data-preset="neighbours"]');
  assert.equal(await page.locator('#currencySelect').inputValue(),'AUDIDR','presets retain currency');
  assert.deepEqual(await page.evaluate(()=>[state.startDate,state.endDate]),periodBefore,'presets retain period');
  await page.click('[data-preset="global"]');
  assert.equal(await page.locator('#chart polyline').count(),4);
  await page.screenshot({path:'/tmp/id-market-world.png',fullPage:true});
  await page.click('[data-collection="themes"]');
  assert.equal(await page.locator('#worldOverview').isVisible(),false);
  for(const [preset,count] of [['globalbanks',3],['tech',4],['digital',3],['resources',4],['automotive',3]]) {
   await page.click(`[data-preset="${preset}"]`);
   assert.equal(await page.locator('#chart polyline').count(),count,preset);
  }
  await page.click('[data-preset="globalbanks"]');
  await chooseView('price');
  assert.equal(await page.locator('#chart polyline').count(),3,'foreign stocks share converted price units');
  await page.click('#stockToggleSummary');
  await page.selectOption('#assetCountry','Australia');
  assert.equal(await page.locator('#stockToggleList input').count(),3);
  assert.match(await page.locator('#stockToggleList').innerText(),/ASX.*AUD/s);
  await page.selectOption('#assetCountry','all');
  await page.click('[data-category="crypto"]');
  assert.equal(await page.locator('#stockToggleList input').count(),2);
  await page.keyboard.press('Escape');
  await page.click('#resetSelections');
  assert.equal(await page.locator('[data-collection="indonesia"]').getAttribute('aria-pressed'),'true');
  await page.click('[data-preset="banks"]');
  assert.equal(await page.locator('#chart [data-series="BBCA"] polyline').getAttribute('stroke'),originalColor,'stable asset colors');
  await page.locator('.comparison-row[data-series="BBCA"]').hover();
  assert.equal(await page.locator('#chart [data-series="BBRI"]').evaluate(el=>el.style.opacity),'0.15');
  await page.locator('h1').hover();
  assert.equal(await page.locator('#chart [data-series="BBRI"]').evaluate(el=>el.style.opacity),'1');
  await chooseView('relative');
  await page.selectOption('#benchmarkSelect','IHSG');
  assert.match(await page.locator('#chartTitle').innerText(),/IHSG/);
  assert.equal(await page.locator('.result-growth').count(),0,'benchmark results do not show Rupiah illustrations');
  await chooseView('growth');
  await page.click('[data-preset="banks"]');
  await chooseView('price');
  assert.equal(await page.locator('#chart polyline').count(),4);
  await page.selectOption('#benchmarkSelect','USDIDR');
  await page.click('#resetSelections');
  assert.equal(await page.locator('#benchmarkSelect').inputValue(),'IDR');
  assert.equal(await page.locator('[data-mode="growth"]').getAttribute('aria-pressed'),'true');
  assert.match(await page.locator('.result-value').first().innerText(),/^Rp/);
  assert.match(await page.locator('.result-growth').first().innerText(),/%$/);
  await page.click('#stockToggleSummary');
  await page.click('[data-category="commodity"]');
  assert.equal(await page.locator('#stockToggleList input').count(),12);
  await page.fill('#stockToggleSearch','nickel');
  assert.equal(await page.locator('#stockToggleList input').count(),1);
  await page.check('#stockToggleList input');
  assert.equal(await page.locator('#chart polyline').count(),5);
  assert.equal(await page.locator('#presetButtons .active').count(),0);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#stockToggleDropdown').getAttribute('open'),null);
  await page.locator('.comparison-row[data-series="NICKEL"]').hover();
  await page.getByRole('button',{name:'Remove Nickel',exact:true}).click();
  assert.equal(await page.locator('#chart polyline').count(),4);
  await page.click('#stockToggleSummary');
  await page.click('#clearComparison');
  assert.match(await page.locator('#chartEmptyState').innerText(),/No lines selected/);
  await page.keyboard.press('Escape');
  await page.click('[data-preset="default"]');
  await chooseView('price');
  assert.match(await page.locator('#chartEmptyState').innerText(),/Use Growth/);
  await chooseView('growth');
  await page.click('#customDates > summary');
  await page.selectOption('#startDate','2020-01-01');
  await page.selectOption('#endDate','2021-01-01');
  assert.match(await page.locator('#chartRangeLabel').innerText(),/Jan 2020 — Jan 2021/);
  assert.equal(await page.locator('#timeframeButtons .active').count(),0);
  await page.click('#closeDatePicker');
  await page.click('[data-range="MAX"]');
  await page.click('#stockToggleSummary');
  await page.click('[data-category="all"]');
  await page.fill('#stockToggleSearch','GOTO');
  await page.check('#stockToggleList input');
  assert.match(await page.locator('#sharedWindowNote').innerText(),/Adjusted to the history/);
  await page.click('#closeAssetPicker');
  await page.click('#resetSelections');
  const overlay=await page.locator('#chartOverlay').boundingBox();
  await page.mouse.move(overlay.x+overlay.width*.6,overlay.y+overlay.height*.4);
  assert.equal(await page.locator('#chartTooltip').getAttribute('aria-hidden'),'false');
  await page.locator('h1').hover();
  assert.equal(await page.locator('#chartTooltip').getAttribute('aria-hidden'),'true');
  await page.click('#changeDiagnostics > summary');
  assert.ok(await page.locator('#changeChart polyline').count()>0);
  await page.click('#changeDiagnostics > summary');
  await page.locator('h1').click();
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'/tmp/id-market-desktop.png',fullPage:true});
  await page.setViewportSize({width:1280,height:800});
  await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'laptop has no horizontal overflow');
  await page.screenshot({path:'/tmp/id-market-laptop.png',fullPage:true});
  // Basic narrow-screen fallback; desktop is the primary layout.
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.click('#stockToggleSummary');
  const picker=await page.locator('.stock-toggle-panel').boundingBox();
  assert.ok(picker.x>=0&&picker.x+picker.width<=390,'selector stays inside viewport');
  await page.keyboard.press('Escape');
  await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
  await page.waitForSelector('#chart polyline');
  assert.equal(await page.locator('#chart polyline').count(),4);
  assert.deepEqual(errors,[]);
  console.log('PASS: simple toolbar, combined results, global themes, world overview, filters, currency switching, desktop layout, presets retaining period/currency, stable colors, linked highlights, removal, clear/recovery, custom dates, benchmark/price switching, chart hover, diagnostics, narrow fallback, and file:// opening.');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
